domain_path: E:\FPGAproject\Zynq7010Oscilloscope2\platform\export\platform\sw\standalone_ps7_cortexa9_0
app_src_dir: E:\FPGA\2025.1\Vitis\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
